language: python
cache: bundler
sudo: false
branches:
    only:
        - master
python:
- 3.4
install:
- pip install -r requirements.txt
before_script:
- flake8 superlists
script:
- py.test superlists
